CREATE TABLE IF NOT EXISTS "offlog_bikes" (
	"id" serial PRIMARY KEY NOT NULL,
	"year" integer NOT NULL,
	"brand" varchar(50) NOT NULL,
	"model" varchar(100) NOT NULL,
	"category" varchar(20) NOT NULL,
	"engine_cc" integer,
	"engine_size" varchar(10),
	"stroke_type" varchar(10),
	"start_type" varchar(20),
	"fuel_system" varchar(30),
	"production_status" varchar(20),
	"market_regions" varchar(100),
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "offlog_user" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "offlog_user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"username" varchar(256),
	"email" varchar(256),
	"password" varchar(256),
	"vehicles_id" integer,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "offlog_vehicle" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "offlog_vehicle_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"brand" varchar(256),
	"model" varchar(256),
	"year" integer,
	"user_id" integer,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "username_idx" ON "offlog_user" USING btree ("username");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "name_idx" ON "offlog_vehicle" USING btree ("name");